### ISSUE TITLE
Allow nvidia driver installer daemonsets for cos and ubuntu to co-exist

### ISSUE THREAD

**Issue by saswatac** [GoogleCloudPlatform/container-engine-accelerators#138]
For clusters having both cos and ubuntu based nodes, it is needed to install both the daemonsets for ubuntu and cos, but with the current setup, only either of them can be installed.

Proposal to allow both the daemonset to be installed -

Make the changes below to preloaded daemonsets https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/nvidia-driver-installer/ubuntu/daemonset-preloaded.yaml and https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml

-> replace the name and labels from "nvidia-driver-installer" to "nvidia-driver-installer-{cos/ubuntu}"

-> add an additional node selector term

```
nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: Exists
              - key: cloud.google.com/gke-os-distribution
                operator: In
                values:
                  - {ubuntu/cos}
```
