### ISSUE TITLE
EGL doesn't work on kubernetes with k8s NVIDIA plugin

### ISSUE THREAD

**Issue by pawel-ziecina** [GoogleCloudPlatform/container-engine-accelerators#94]
Trying to run CARLA simulator in offscreen/EGL mode on GKE but failed.
Simulator uses nvidia/opengl image.

It runs correctly on nvidia-docker2 where drivers are mounted in /usr/lib/x86_64-linux-gnu. But on GKE drivers by default are attached by nvidia-plugin in /usr/local/nvidia/lib64.

Shall be new directories with library added to LD_LIBRARY_PATH of newly started container?

**Comment by jiayingz** [comment]
Thanks for reporting this, @pawel-ziecina 
Have you tried to add the following volume mount and see whether it makes your CARLA simulator work?

```
      volumeMounts:
        - name: "nvidia-libraries"
          mountPath: "/usr/lib/x86_64-linux-gnu"
  volumes:
    - name: "nvidia-libraries"
      hostPath:
        path: "/home/kubernetes/bin/nvidia/lib"

```
